//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_srinput : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean touchpadclick
        {
            get
            {
                return SteamVR_Actions.srinput_touchpadclick;
            }
        }
        
        public virtual SteamVR_Action_Boolean grip
        {
            get
            {
                return SteamVR_Actions.srinput_grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean trigger
        {
            get
            {
                return SteamVR_Actions.srinput_trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean touchpadtouch
        {
            get
            {
                return SteamVR_Actions.srinput_touchpadtouch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 touchpadposition
        {
            get
            {
                return SteamVR_Actions.srinput_touchpadposition;
            }
        }
        
        public virtual SteamVR_Action_Pose pose
        {
            get
            {
                return SteamVR_Actions.srinput_pose;
            }
        }
    }
}
