//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public struct Size2D
{
	public int Width;
	public int Height;

	public Size2D(int w,int h)
	{
		Width = w;
		Height = h;
	}
}

